travis:
  secure:
    BINSTAR_TOKEN: gIBhyp4CVHIGPeuCaGiV2lDdecXlF45vEfohpPHNYYqH99boyiw6SmbXZMHOMq5NWGTJ0Q0dV7ODsqIvcDy2ySQDZHZrnLe3AoiDoTV+zh2TzIo44Mv4qfwrzFp6l0UWJ6uM3M4ZogRO0NJARW9liPlaiv6RUkYHPWneT3sbG+LOAsMx7DiXZxHNkawOEBuR4Ht+cNYv6XvZzj1rFGHX8yspbuwp4OZzmCPCRoi5b7ThX7d7GbO9SUCh2Rz9POC0Yw4erPBcgmiGB9W7M5wRvLMLPi6Iaq1zD8h5O6kMGsxSlMjYOlnY1FoFLjmxSxMVDUQA8B6jsllKX+eEgnF41KAm+H6Jqt2Dfu/MLSLGI3gfpYI+UnnGbklMZ9dEdSy63QwUkwQVfb6vpKgzgbqSU5JjtaufB2JOo1Vq+7vg/r4l+KGatnTHPT34u5KTvnHYdFrL5mUh4gXIuPiD0he7bDCUzsbxSXvhP0xmSm0i8sTPEnT8ALq36ZkUwuI5ioK7G3yDipgS0E4XOXL+qc6LgUPr3xJlsPPf6dd+VAYziu3GvWwNW/Y/0C91gDpXFX3pX75jfSja0hGfXlMSJDba+kBjf9bY9FREmwzu66uXICTgtq3OFR17kk+MVPCOlQt64wPJnHs44te0Ux5kx7nfRUsQKaSNeCueRh1vrUYETzQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
